### ISSUE TITLE
Compatibility for Idea 2020.3

### ISSUE THREAD

**Issue by Jawtoch** [Phosphorus15/intellij-prolog#63]
# Hello
Are you planning to update the Prolog plugin language for Idea 2020.3 ?
Best regards

**Comment by klesun** [comment]
+1. When one tries to install, he gets:

> Plugin 'Prolog' (version '0.1.2.2-2') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is IU-203.5981.155

**Comment by klesun** [comment]
@Phosphorus15 I'm not sure, but I think you want to add something like `<idea-version since-build="203.5981.155"/>` in your [`plugin.xml`](https://github.com/Phosphorus15/intellij-prolog/blob/master/src/main/resources/META-INF/plugin.xml). I think it's absence is the reason each time you compile it automagically sets your current IDE version as the only allowed for the jar, forcing you to re-upload updates for every minor version of IDEA.

Example:
https://github.com/klesun/deep-assoc-completion/blob/5d291fef17225e705c83ece67d82d0afd4edcc47/resources/META-INF/plugin.xml#L56

**Comment by rombru** [comment]
Please, could you accept this pr ? I'm stuck and that plugin really helps me

**Comment by Phosphorus15** [comment]
> Please, could you accept this pr ? I'm stuck and that plugin really helps me

If you need this plugin urgently I'd suggest you build your own copy ( because the long moderation prcoess of plugin market ), otherwise I will release a binary before the market do, just wait for a little while.

**Comment by klesun** [comment]
I still can't see the new version in the [jetbrains repository](https://plugins.jetbrains.com/plugin/13954-prolog/versions). Is the update still awaiting jetbrains review? Isn't it normally supposed to take just two days...

**Comment by simonprovost** [comment]
Still got the error.. what's the best option to solve the issue, please?
